### ISSUE TITLE
Recurring event icon TB 102

### ISSUE THREAD

**Issue by Gendji** [Aris-t2/CustomCSSforTb#11]
Hi,

I upgraded to TB version 102 and somehow there is an icon now in the title of repeating events.

Picture of it here: https://bug1674912.bmoattachments.org/attachment.cgi?id=9264242.

Is it possible to remove that somehow with CustomCSSforTb?

**Comment by Aris-t2** [comment]
If you want to remove the "repeat" icon, add this to your `my_userChrome.css` file or at the bottom of the `userChrome.css` file:

```css
.item-recurrence-icon {
  display: none !important;
}
```
