### ISSUE TITLE
Removing rounded corners from the menus of thunderbird 102

### ISSUE THREAD

**Issue by pitsi** [Aris-t2/CustomCSSforTb#13]
1. Describe the issue
One of the annoying changes I have noticed in tb 102 is the rounded corners that appear in menus, as seen in the screenshots below. They have that w11 look with the rounded corners, the ones that appear white do not follow the gtk theme of the desktop and when the window is inactive, the text on the main toolbar almost invisible (light grey letters on dark grey background.
I tried your css, I played around with its options but it does not seem to solve anything of the above, so the main question here is if any of this is doable via css.

2. What should have happened instead?
A lot, as I described above. I would be happy even if I managed to only get the right-click white menus to follow the gtk theme. 

3. Steps to reproduce the issue?
Install or upgrade to thunderbird 102 on a linux distro, prefereably on one using a dark gtk theme. 

4. SCREENSHOTS with/without this projects files
The all white right right click menu with the rounded corners

![2022-07-03-184532_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/177048073-00ad79d8-625c-446c-a20e-0b4f6cefc360.png)

The rounded menus from the main toolbar

![2022-07-03-184613_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/177048106-b9d9c5da-01ba-4e37-9bf3-191429158a8e.png)

5. System information
- OS & OS version: Debian testing/unstable x64
- OS theme name: Numix
- DPI / HiDPI resolution: 96
- Thunderbird version: 102b7 
- Thunderbird theme / lw-theme: System theme - Auto
- This projects settings the issue occurs with:

**Comment by Aris-t2** [comment]
This should do the job:

```css
menupopup {
  --panel-border-radius: 0px !important;
}
```

**Comment by pitsi** [comment]
Thank you very much! Finally a good looking tb 102!

**Comment by Aris-t2** [comment]
I will add this as an option to the main project:

```css
#appMenu-popup,
menupopup {
  border-radius: 0px !important;
  --panel-border-radius: 0px !important;
}
```

>I assume there is no way to make the right click menus follow the gtk theme, like ff does.

It might be. We need to look into the code Firefox uses for menus there.

**Comment by pitsi** [comment]
Do I have to edit the file again and add the lines you have added on that comment?

**Comment by Aris-t2** [comment]
If the changes should also affect main browser menu too, then yes. ;-)

**Comment by pitsi** [comment]
I added the extra lines of code but nothing changed, or at least not something noticeable.
The menus still have square corners and the colors mentioned above. I am always talking about tb here, I have not touched ff.

**Comment by Aris-t2** [comment]
I'm talking about Thunderbirds main menu.

![image](https://user-images.githubusercontent.com/6013569/178148210-ae761b64-f720-4617-94ba-01f8eb1c3e7f.png)
![image](https://user-images.githubusercontent.com/6013569/178148247-52a482d8-b905-4bf3-9d4a-03f3582fcf10.png)

**Comment by pitsi** [comment]
I have set the menubar to be always visible, so I have never noticed that menu. It's corners are square now.
However, I think it is the same "attribute" for any of the menus from the menu bar, for which I have posted a screenshot (the help menu above).

**Comment by pitsi** [comment]
One wierd bug that I noticed on the white right-click menus of tb 102. While all the right click entries are black text on white background and black text on light grey background, completely ignoring the gtk theme as seen here

![2022-07-11-144319_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/178257790-088407e2-6ebd-4225-9ad9-38e05e7037c2.png)

the entry for copy link location suddenly follows the gtk theme when it is selected, which on my end is white text on orange background

![2022-07-11-144348_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/178258585-89ce30a5-5a2e-49e0-a013-3ee87d718a92.png)

I hope this helps in creating that rule that will force tb 102 follow the gtk theme.

p.s. The above is unrelated to the css rule you posted here.

**Comment by Aris-t2** [comment]
You can try this code to force custom colors on menuitems:

```css
menupopup menuitem {
  background: white !important;
  color: black !important;
}

menupopup menuitem:hover {
  background: lightgrey !important;
  color: black !important;
}

menupopup menuitem[_moz-menuactive="true"],
menupopup menuitem[_moz-menuactive="true"]:hover {
  background: Highlight !important;
  color: HighlightText !important;
}
```

`Highlight` and `HighlightText` are color variables defined by your OS theme.

Try the last part of the code first.
