### ISSUE TITLE
Spaces Toolbar handling

### ISSUE THREAD

**Issue by GaVenga** [Aris-t2/CustomCSSforTb#15]
How To Hide Spaces Toolbar _**Button**_ (Linux) 102.11.1

**Comment by Aris-t2** [comment]
Could you post a screenshot?

**Comment by GaVenga** [comment]
![Thunderbi-1](https://github.com/Aris-t2/CustomCSSforTb/assets/49439346/c5382eac-f760-4fe6-9044-d0d45add8e8f)
![thubi2](https://github.com/Aris-t2/CustomCSSforTb/assets/49439346/a1579884-08ed-4281-91ec-2b557450cfd7)

**Comment by Aris-t2** [comment]
Try this code inside `my_userChrome.css` file:

```css
#spacesPinnedButton {
  display: none !important;
}
```
